### Get all endpoints
GET http://127.0.0.1:5000/endpoints?sid=
### Get a random question and 4 values as anwsers
GET http://127.0.0.1:5000/random?sid=
### DISABLED ENDPOINT (used to return all questions)
GET http://127.0.0.1:5000/all?sid=
### Get ranking/scoreboard (top10)
GET http://127.0.0.1:5000/scoreboard?sid=
### get graph(stats) to display on website
GET http://127.0.0.1:5000/graph?sid=
### Check if user logged right answer in
GET http://127.0.0.1:5000/check?q=Welches%20OS%20wird%20am%20meisten%20verwendet%3F&a=Wrong%20Answer&sid=
### Register session to get sessionid for auth for other endpoints (sid delted from ram if scoreboard endpoint hit, therefore only one scoreboard entry per sid)
GET http://127.0.0.1:5000/register
### Get users score and lifes to display on website:
GET http://127.0.0.1:5000/update?sid=
### Update users score and lifes (cr=yes-->+100score||cr=no-->-100score&&-1life)
GET http://127.0.0.1:5000/update?sid=&cr=yes
### Write userobject from ram to scoreboard.csv
POST http://127.0.0.1:5000/scoreboard?name=xnacly&sid=
