GET http://127.0.0.1:5000/endpoints
###
GET http://127.0.0.1:5000/random
###
GET http://127.0.0.1:5000/all
###
GET http://127.0.0.1:5000/scoreboard
###
POST http://xnaclyy.pythonanywhere.com/scoreboard?name=xnacly&score=900000&auth=